### ISSUE TITLE
[flutter pub get] Failed get packages

### ISSUE THREAD

**Issue by Lailan** [victormanuelfrancodev/share_social_media_plugin#1]
Hi.

When i try install de pub in my project or try build iOS example project, i get the following error: 

`Because testiosshare depends on flutter_twitter_ab ^0.0.1 which doesn't match any versions, version solving failed.
pub get failed (1; Because testiosshare depends on flutter_twitter_ab ^0.0.1 which doesn't match any versions, version solving failed.)`

Can someone helps me?

**Comment by victormanuelfrancodev** [comment]
Thank you for report that 
I am using this plugin and apparently it was updated, I launched a plugin update already with the updated version,
I did tests and it is ready.
Please update to  new version
share_social_media_plugin: ^1.1.5 

Thank you so much
