### ISSUE TITLE
Uri permission

### ISSUE THREAD

**Issue by Developer-Vandi** [victormanuelfrancodev/share_social_media_plugin#2]
Syncing files to device motorola one vision...
Reloaded 0 of 810 libraries in 736ms.
D/assetFile(19410): assets/images/app_icon.png
D/error   (19410): file:///storage/emulated/0/Android/data/com.altaloop.doit100days/files/Pictures/share_image_1588164789023.png exposed beyond app through ClipData.Item.getUri()
D/assetFile(19410): assets/images/app_icon.png
D/error   (19410): file:///storage/emulated/0/Android/data/com.altaloop.doit100days/files/Pictures/share_image_1588164806911.png exposed beyond app through ClipData.Item.getUri()

**Comment by victormanuelfrancodev** [comment]
it is subject of a permission, I will add it, update the repository, thanks!

**Comment by victormanuelfrancodev** [comment]
added : 

StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
StrictMode.setVmPolicy(builder.build());

please download the new version. 
share_social_media_plugin: ^1.1.6
