### ISSUE TITLE
Null Safety migration

### ISSUE THREAD

**Issue by Skquark** [victormanuelfrancodev/share_social_media_plugin#4]
In case anyone still using this and updated Flutter, here's a Null-Safety migrated version you can use.
```yaml
share_social_media_plugin: 
    git: https://github.com/Skquark/share_social_media_plugin.git
```
If you want me to make a PR with it to officially refresh the plug-in, I'd be happy to provide.

**Comment by victormanuelfrancodev** [comment]
@Skquark  hello! 
Of course!, please make the PR. 
Thank you a lot!
